[project]
name = "instavirtualstagging"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cloudinary>=1.44.1",
    "moviepy>=2.2.1",
    "pillow>=11.3.0",
    "python-dotenv>=1.1.1",
]
